name: Build and push docker image

on:
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - '.github/**'

env:
  GH_USER: Klazomenai
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push-image:
    name: Build and push backend image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Repository Name
        run: |
          echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
          echo "REPO_NAME=${GITHUB_REPOSITORY}" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "${{ env.GH_USER }}"

      - name: Log-in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.GH_USER }}
          password: ${{ secrets.GH_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.REGISTRY }}/${{ env.REPO_NAME }}"

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:/"
          push: true
          tags: "${{ steps.meta.outputs.tags }}-${{ env.SHORT_SHA }}"
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set Environment Variables
        run: |
          if [ "${{ GITHUB_REF }}" == "refs/heads/develop" ]; then
            echo "foo"
          elif [ "${{ GITHUB_REF }}" == "refs/heads/main" ]; then
            echo "bar"
          fi

      - name: Deploy the Docker Image
        run: |
          echo "Tags with short sha: ${{ steps.meta.outputs.tags }}-${{ env.SHORT_SHA }}"
