name: "Integration Tests"

on:
  pull_request:
    branches: [ master ]

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: git checkout

    - name: Sed branch out of ref
      run: echo $GITHUB_HEAD_REF $GITHUB_RUN_NUMBER
