name: "Integration Tests"

on:
  pull_request:
    branches: [ master ]

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: git checkout
      with:
        repository: clearmatics/charts-ose-helm3
        ref: helm2to3start

    - name: Set path
      run: echo '::set-env name=CHART_PATH::stable/'$GITHUB_HEAD_REF
    - name: Get path
      run: echo 'The chart path is' $CHART_PATH

    - uses: azure/setup-helm@v1
      with:
        version: '3.2.4'
      id: install

    - name: Deploy the chart
      run: |
        helm upgrade $GITHUB_HEAD_REF $CHART_PATH --install --namespace=default
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
