name: "Integration Tests"

on:
  pull_request:
    branches:
      - master
      - foo
      - bar
      - biscuit

jobs:
  integration_tests:

    runs-on: ubuntu-latest
    if: |
      github.head_ref ==  'foo' ||
      github.head_ref == 'bar' ||
      github.head_ref == 'quercus-robur'

    steps:
    - uses: actions/checkout@v2
      name: git checkout

    - name: Set useful variables
      run: |
        echo "{CHART_PATH}={stable/$GITHUB_HEAD_REF}" >> $GITHUB_ENV
        echo "{ACTOR_LOWERCASE}={$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')}" >> $GITHUB_ENV
        echo "{SHORT_SHA}={$(echo $GITHUB_SHA|head -c 7)}" >> $GITHUB_ENV


    - name: Get useful variables
      run: |
        echo 'Chart path: '$CHART_PATH
        echo 'Actor: '$GITHUB_ACTOR
        echo 'Actor Lowercase: '$ACTOR_LOWERCASE
        echo 'Short SHA: '$SHORT_SHA
        echo 'GitHub Run ID: '$GITHUB_RUN_ID

    - name: Sed branch out of ref
      run: |
        echo $GITHUB_HEAD_REF
        echo $GITHUB_RUN_NUMBER
        echo $GITHUB_REF
        echo github.ref
