name: "Integration Tests"

on:
  pull_request:
    branches: [ master ]

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: git checkout
      with:
        repository: clearmatics/charts-ose-helm3
        ref: master

    - name: Set path
      run: echo '::set-env name=CHART_PATH::stable/'$GITHUB_HEAD_REF
    - name: Get path
      run: echo 'The chart path is' $CHART_PATH
    - name: Check path
      run: ls $CHART_PATH

    - name: 'Test Helm chart'
      uses: 'deliverybot/helm@v1'
      with:
        helm: helm3
        release: $GITHUB_HEAD_REF
        namespace: $GITHUB_HEAD_REF
        chart: $CHART_PATH
        values: stable/autonity/values.yml
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
