name: "Integration Tests"

on:
  pull_request:
    branches: [ master ]

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: git checkout
      with:
        repository: clearmatics/charts-ose-helm3
        ref: master

    - name: Sed branch out of ref
      run: echo $GITHUB_HEAD_REF

    - name: 'Test Helm chart'
      uses: 'deliverybot/helm@v1'
      with:
        helm: helm3
        release: $GITHUB_HEAD_REF
        namespace: $GITHUB_HEAD_REF
        chart: stable/$GITHUB_HEAD_REF
        value-files: stable/$GITHUB_HEAD_REF
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
