name: "Integration Tests"

on:
  pull_request:
    branches:
      - master
      - foo
      - bar
      - biscuit

jobs:
  integration_tests:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: git checkout
      if: github.head_ref ==  'foo' || github.head_ref == 'bar' || github.head_ref == 'biacuit'

    - name: Sed branch out of ref
      run: |
        echo $GITHUB_HEAD_REF
        echo $GITHUB_RUN_NUMBER
        echo $GITHUB_REF
        echo github.ref
