name: "Integration Tests"

on:
  pull_request:
    branches:
      - master
      - foo
      - bar
      - biscuit

jobs:
  integration_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: git checkout
      if: contains(github.ref, 'foo') || contains(github.ref, 'bar' || contains(github.ref, 'biscuit')

    - name: Sed branch out of ref
      if: githiub.ref ==  'foo' || github.ref == 'bar' || github.ref == 'biscuit')
      run: echo $GITHUB_HEAD_REF $GITHUB_RUN_NUMBER
