name: "Integration Tests and Publish on Tag"

on:
  push:
    tags:
    - 'foo-v[0-9]+.[0-9]+.[0-9]+*'
    - 'baz-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  integration_tests_publish_on_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Echo
      run: |
        echo '::set-env name=TAG::'${GITHUB_REF##*/}
        echo '::set-env name=CHART_NAME::'$(echo $TAG | awk -F '-' '{print $1}')
        echo 'CHART_NAME: '$CHART_NAME
        echo 'GITHUB_REF short '${GITHUB_REF##*/}
        echo 'GITHUB_HEAD_REF '${GITHUB_HEAD_REF}
        echo 'TAG: '$TAG
