name: "Integration Tests and Publish on Tag"

on:
  push:
    tags:
    - 'foo-[0-9]+.[0-9]+.[0-9]+*'
    - 'foo-bar-[0-9]+.[0-9]+.[0-9]+*'
    - 'foo-baz-[0-9]+.[0-9]+.[0-9]+*'

jobs:
  integration_tests_publish_on_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Set CHART_NAME variable
      run: |
        echo '::set-env name=CHART_NAME::'$(echo ${GITHUB_REF##*/} | | sed -E s'/-[0-9]+\.[0-9]+\.[0-9]+$//g')
        echo '::set-env name=ACTOR_LOWERCASE::'$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')
        echo '::set-env name=SHORT_SHA::'$(echo $GITHUB_SHA|head -c 7)

    - name: Get CHART_NAME variables
      run: |
        echo 'Chart name: '$CHART_NAME
        echo 'Chart path: '$CHART_PATH
        echo 'Actor: '$GITHUB_ACTOR
        echo 'Actor Lowercase: '$ACTOR_LOWERCASE
        echo 'Short SHA: '$SHORT_SHA
        echo 'GitHub Run ID: '$GITHUB_RUN_ID
        echo 'GitHub Event Name: '$GITHUB_EVENT_NAME
        echo 'GitHub Ref: '$GITHUB_REF
        echo 'GitHub Head Ref: '$GITHUB_HEAD_REF
        echo 'GitHub Base Ref: '$GITHUB_BASE_REF
