name: "Integration Tests and Publish on Tag"

on:
  push:
    tags:
    - 'foo-v[0-9]+.[0-9]+.[0-9]+*'
    - 'baz-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  integration_tests_publish_on_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Set useful variables
      run: |
        echo '::set-env name=TAG::'$GITHUB_REF
        echo '::set-env name=TAG_TWO::blah/'$GITHUB_REF
        echo '::set-env name=CHART_NAME::'$(echo sue-v0.0.1 | awk -F '-' '{print $1}')
        echo '::set-env name=CHART_NAME_TWO::sue-v0.0.1'
        echo "::set-env name=MY_ACTION_SCRIPT::.github/step_param_from_env.sh"
    - name: Get useful variables
      run: |
        echo "MY_ACTION_SCRIPT: ${{env.MY_ACTION_SCRIPT}}"
        echo 'MY_ACTION_SCRIPT: ${{env.MY_ACTION_SCRIPT}}'
        echo 'MY_ACTION_SCRIPT: '${{env.MY_ACTION_SCRIPT}}
        echo 'MY_ACTION_SCRIPT: '${MY_ACTION_SCRIPT}
        echo 'MY_ACTION_SCRIPT: '$MY_ACTION_SCRIPT
        echo 'CHART_NAME: '$CHART_NAME
        echo 'CHART_NAME_TWO: '$CHART_NAME_TWO
        echo 'GITHU_REF:' $GITHUB_REF
        echo 'GITHUB_REF short '${GITHUB_REF##*/}
        echo 'TAG: '$TAG
        echo 'TAG_TWO: '$TAG_TWO
