name: release-test

on:
  release:
    types:
      - created

jobs:
  release-test:
    name: "Test release vars"
    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Get vars from git"
        id: git_vars
        run: |
          echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=COMMIT_HASH::$(git rev-parse --short HEAD)
          echo ::set-output name=REPOSITORY_LOWERCASE::$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')

      - name: Configure Docker
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: "Echo vars from git"
        run: |
          echo ${{ steps.git_vars.outputs.TAG }}
          echo ${{ steps.git_vars.outputs.COMMIT_HASH }}

      - name: Build Tag and Push
        run: |
          docker build . --tag ghcr.io/${{ steps.git_vars.outputs.REPOSITORY_LOWERCASE }}:latest
          docker tag ghcr.io/${{ steps.git_vars.outputs.REPOSITORY_LOWERCASE }}:latest ghcr.io/${{ steps.git_vars.outputs.REPOSITORY_LOWERCASE }}:${{ steps.git_vars.outputs.TAG }}
          docker push ghcr.io/${{ steps.git_vars.outputs.REPOSITORY_LOWERCASE }}:latest
          docker push ghcr.io/${{ steps.git_vars.outputs.REPOSITORY_LOWERCASE}}}:${{ steps.git_vars.outputs.TAG }}
