name: Log timeout test

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build Dashboards
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Capture Build Job Start Time
        run: echo "$(date +%s)" > build-job-start-time.txt

      - name: Upload Build Job Start Time
        uses: actions/upload-artifact@v4
        with:
          name: build-job-start-time
          path: build-job-start-time.txt

      - name: Sleep 60 Seconds to Trigger Timeout
        run: sleep 60

      - name: Capture Build Job End Time
        if: always()
        run: echo "$(date +%s)" > build-job-end-time.txt

      - name: Upload Build Job End Time
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-job-end-time
          path: build-job-end-time.txt

  report:
    name: Report Job Status
    runs-on: ubuntu-latest
    if: always()
    needs:
      - build

    env:
      REPORT_ON_SUCCESS: "false"

    steps:
      - name: Download Build Job Start Time
        uses: actions/download-artifact@v4
        with:
          name: build-job-start-time
          path: .

      - name: Download Build Job End Time
        uses: actions/download-artifact@v4
        with:
          name: build-job-end-time
          path: .

      - name: Calculate Total Execution Time
        run: |
          BUILD_JOB_START_TIME=$(cat build-job-start-time.txt)
          BUILD_JOB_END_TIME=$(cat build-job-end-time.txt)
          BUILD_JOB_RUNTIME=$(( BUILD_JOB_END_TIME - BUILD_JOB_START_TIME ))
          echo "BUILD_JOB_RUNTIME=$TOTAL_RUNTIME" >> $GITHUB_ENV
          echo "BUILD_JOB_START_TIME: " $BUILD_JOB_START_TIME
          echo "BUILD_JOB_END_TIME: " $BUILD_JOB_END_TIME
          echo "BUILD_JOB_RUNTIME: " $BUILD_JOB_RUNTIME

      - name: Debug API Response
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}"
